# Generated by Django 4.2.23 on 2025-07-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='player_name',
            field=models.CharField(max_length=255),
        ),
    ]
